// src/Components/CocktailCard.vue
<template>
  <div :class="['bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-all h-full flex flex-col relative', !available ? 'opacity-60' : '', isHidden ? 'ring-2 ring-red-300' : '']">
    
    <!-- Badge de disponibilité (en haut à droite) -->
    <div v-if="barInventory.size > 0" class="absolute top-2 right-2 z-10">
      <span v-if="available" class="inline-flex items-center gap-1 px-2 py-1 bg-green-500 text-white text-xs font-semibold rounded-full shadow-md">
        ✓ Réalisable
      </span>
      <span v-else class="inline-flex items-center gap-1 px-2 py-1 bg-orange-500 text-white text-xs font-semibold rounded-full shadow-md">
        ⚠️ {{ missingIngs.length }} manquant{{ missingIngs.length > 1 ? 's' : '' }}
      </span>
    </div>

    <div v-if="cocktail.Image && isExpanded" class="h-32 sm:h-40 md:h-48 overflow-hidden bg-gray-200 flex-shrink-0">
      <img
        :src="cocktail.Image"
        :alt="cocktail.Name"
        class="w-full h-full object-cover"
        @error="hideImage"
      />
    </div>

    <div class="p-3 md:p-4 flex-1 flex flex-col">
      <div class="flex justify-between items-start mb-2 md:mb-3">
        <div class="flex-1">
          <h3 :class="['text-base md:text-lg font-bold', available ? 'text-gray-800' : 'text-gray-400']">
            {{ cocktail.Name }}
          </h3>
          <!-- Message si cocktail masqué -->
          <p v-if="isHidden" class="text-xs text-red-600 mt-0.5">
            Masqué en mode Drinker
          </p>
        </div>
        <button
          v-if="currentProfile && appMode === 'drinker'"
          @click="() => onToggleFavorite(cocktail.id)"
          :class="['p-1.5 md:p-2 rounded-full transition-colors flex-shrink-0', isFavorite ? 'text-yellow-500 bg-yellow-50' : 'text-gray-400 hover:text-yellow-500 hover:bg-gray-50']"
        >
          <Star :size="18" :fill="isFavorite ? 'currentColor' : 'none'" />
        </button>
      </div>

      <div class="flex items-center gap-1.5 mb-2 md:mb-3 flex-wrap">
        <span class="px-2 py-0.5 bg-blue-100 text-blue-800 text-xs md:text-sm rounded-full">
          {{ cocktail.spiritType }}
        </span>
        <span class="px-2 py-0.5 bg-purple-100 text-purple-800 text-xs md:text-sm rounded-full">
          {{ cocktail.family.replace('_', ' ') }}
        </span>
        <span v-if="cocktail.Season" class="px-2 py-0.5 bg-pink-100 text-pink-800 text-xs md:text-sm rounded-full">
          {{ cocktail.Season }}
        </span>
      </div>

      <div v-if="currentProfile && appMode === 'drinker'" class="flex items-center gap-0.5 mb-2 md:mb-3">
        <button
          v-for="star in 5"
          :key="star"
          @click="() => onSetRating(cocktail.id, star)"
          :class="[star <= rating ? 'text-yellow-400' : 'text-gray-300', 'hover:text-yellow-400 transition-colors']"
        >
          <Star :size="16" :fill="star <= rating ? 'currentColor' : 'none'" />
        </button>
      </div>

      <button
        v-if="appMode === 'bartender'"
        @click="() => onToggleHidden(cocktail.id)"
        :class="['w-full mb-2 py-1.5 md:py-2 rounded-lg font-medium text-xs md:text-sm', isHidden ? 'bg-red-100 text-red-700 hover:bg-red-200' : 'bg-gray-100 text-gray-700 hover:bg-gray-200']"
      >
        {{ isHidden ? 'Afficher' : 'Masquer' }}
      </button>

      <button
        @click="toggleExpanded"
        class="w-full flex items-center justify-between text-blue-600 hover:text-blue-800 font-medium mb-2 md:mb-3 text-sm"
      >
        <span>{{ isExpanded ? '- Recette' : '+ Recette' }}</span>
        <component :is="isExpanded ? 'ChevronUp' : 'ChevronDown'" :size="18" />
      </button>

      <div v-if="isExpanded" class="border-t pt-2 md:pt-3 mt-2 md:mt-3 space-y-2 md:space-y-3">
        <div class="space-y-1">
          <h4 class="font-semibold text-gray-700 text-sm">Ingrédients:</h4>
          <div v-for="(ing, idx) in cocktail.Recipe" :key="idx" class="flex justify-between text-xs md:text-sm gap-2">
            <span :class="ing.Type !== 'garnish' && !barInventory.has(ing.Ingredient) ? 'text-red-500 font-medium' : 'text-gray-700'">
              <span v-if="ing.Type !== 'garnish' && !barInventory.has(ing.Ingredient)">❌ </span>
              <span v-else-if="ing.Type !== 'garnish'">✓ </span>
              {{ ing.Ingredient }}
            </span>
            <span class="text-gray-500">
              <span v-if="ing.Oz">{{ ing.Oz }} oz</span>
              <span v-if="ing.Ml"> ({{ ing.Ml }} ml)</span>
            </span>
          </div>
        </div>

        <!-- Liste des ingrédients manquants -->
        <div v-if="!available && missingIngs.length > 0" class="bg-orange-50 border border-orange-200 rounded-lg p-2">
          <p class="text-xs font-semibold text-orange-800 mb-1">Ingrédients manquants :</p>
          <ul class="text-xs text-orange-700 space-y-0.5">
            <li v-for="(ing, idx) in missingIngs" :key="idx">• {{ ing.Ingredient }}</li>
          </ul>
        </div>

        <button
          v-if="appMode === 'drinker' && currentProfile && available"
          @click="() => onOrder(cocktail)"
          class="w-full py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 font-medium text-sm"
        >
          Commander ce cocktail
        </button>

        <div v-if="currentProfile && appMode === 'drinker'" class="space-y-2">
          <h4 class="font-semibold text-gray-700 text-sm">Notes personnelles:</h4>
          <textarea
            :value="note"
            @input="e => onSaveNote(cocktail.id, e.target.value)"
            placeholder="Ajoute tes notes..."
            class="w-full p-2 border rounded-lg text-xs md:text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            rows="2"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
import { Star, ChevronDown, ChevronUp } from 'lucide-vue-next';

const props = defineProps({
  cocktail: Object,
  appMode: String,
  currentProfile: [String, Number],
  barInventory: Object,
  favorites: Object,
  userRatings: Object,
  userNotes: Object,
  isHidden: Boolean,
  onToggleFavorite: Function,
  onSetRating: Function,
  onSaveNote: Function,
  onOrder: Function,
  onToggleHidden: Function
});

const isExpanded = ref(false);
const isFavorite = computed(() => props.favorites.has(props.cocktail.id));
const rating = computed(() => props.userRatings[props.cocktail.id] || 0);
const note = computed(() => props.userNotes[props.cocktail.id] || '');
const available = computed(() => 
  Array.isArray(props.cocktail.Recipe) && 
  props.cocktail.Recipe.every(ing => 
    ing.Type === 'garnish' || 
    ((props.barInventory || new Set()).has(ing.Ingredient))
  )
);
const missingIngs = computed(() => 
  Array.isArray(props.cocktail.Recipe) 
    ? props.cocktail.Recipe.filter(ing => 
        ing.Type !== 'garnish' && 
        !(props.barInventory || new Set()).has(ing.Ingredient)
      ) 
    : []
);

function toggleExpanded() {
  isExpanded.value = !isExpanded.value;
}

function hideImage(e) {
  e.target.style.display = 'none';
}
</script>

// src/components/CocktailCard.jsx

// ============================================
// COCKTAIL CARD COMPONENT
// ============================================
import { Star, ChevronDown, ChevronUp } from 'lucide-react';

export const CocktailCard = ({ 
    cocktail, 
    appMode,
    currentProfile,
    barInventory, 
    favorites, 
    userRatings, 
    userNotes,
    isHidden,
    onToggleFavorite, 
    onSetRating, 
    onSaveNote, 
    onOrder,
    onToggleHidden
    }) => {
    const [isExpanded, setIsExpanded] = useState(false);
    const isFavorite = favorites.has(cocktail.id);
    const rating = userRatings[cocktail.id] || 0;
    const note = userNotes[cocktail.id] || '';
    
    const available = cocktail.Recipe.every(ing => 
        ing.Type === 'garnish' || barInventory.has(ing.Ingredient)
    );
    
    const missingIngs = cocktail.Recipe.filter(ing => 
        ing.Type !== 'garnish' && !barInventory.has(ing.Ingredient)
    );

    return (
        <div className={`bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-all ${
        !available ? 'opacity-60' : ''
        } ${isHidden ? 'ring-2 ring-red-300' : ''}`}>
        {cocktail.Image && (
            <div className="h-48 overflow-hidden bg-gray-200">
            <img 
                src={cocktail.Image} 
                alt={cocktail.Name}
                className="w-full h-full object-cover"
                onError={(e) => e.target.style.display = 'none'}
            />
            </div>
        )}
        
        <div className="p-6">
            <div className="flex justify-between items-start mb-3">
            <div className="flex-1">
                <h3 className={`text-xl font-bold ${available ? 'text-gray-800' : 'text-gray-400'}`}>
                {cocktail.Name}
                </h3>
                {!available && (
                <p className="text-xs text-red-600 mt-1">
                    Manque {missingIngs.length} ingrédient{missingIngs.length > 1 ? 's' : ''}
                </p>
                )}
                {isHidden && (
                <p className="text-xs text-red-600 mt-1">Masqué en mode Drinker</p>
                )}
            </div>
            {currentProfile && appMode === 'drinker' && (
                <button
                onClick={() => onToggleFavorite(cocktail.id)}
                className={`p-2 rounded-full transition-colors ${
                    isFavorite ? 'text-yellow-500 bg-yellow-50' : 'text-gray-400 hover:text-yellow-500 hover:bg-gray-50'
                }`}
                >
                <Star size={20} fill={isFavorite ? 'currentColor' : 'none'} />
                </button>
            )}
            </div>

            <div className="flex items-center gap-2 mb-4 flex-wrap">
            <span className="px-3 py-1 bg-blue-100 text-blue-800 text-sm rounded-full">
                {cocktail.spiritType}
            </span>
            <span className="px-3 py-1 bg-purple-100 text-purple-800 text-sm rounded-full">
                {cocktail.family.replace('_', ' ')}
            </span>
            {cocktail.Season && (
                <span className="px-3 py-1 bg-pink-100 text-pink-800 text-sm rounded-full">
                {cocktail.Season}
                </span>
            )}
            {available && (
                <span className="px-3 py-1 bg-green-100 text-green-800 text-sm rounded-full">
                ✓ Disponible
                </span>
            )}
            </div>

            {currentProfile && appMode === 'drinker' && (
            <div className="flex items-center gap-1 mb-4">
                {[1, 2, 3, 4, 5].map(star => (
                <button
                    key={star}
                    onClick={() => onSetRating(cocktail.id, star)}
                    className={`${star <= rating ? 'text-yellow-400' : 'text-gray-300'} hover:text-yellow-400 transition-colors`}
                >
                    <Star size={18} fill={star <= rating ? 'currentColor' : 'none'} />
                </button>
                ))}
            </div>
            )}

            {appMode === 'bartender' && (
            <button
                onClick={() => onToggleHidden(cocktail.id)}
                className={`w-full mb-3 py-2 rounded-lg font-medium text-sm ${
                isHidden 
                    ? 'bg-red-100 text-red-700 hover:bg-red-200' 
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                }`}
            >
                {isHidden ? 'Afficher en mode Drinker' : 'Masquer en mode Drinker'}
            </button>
            )}

            <button
            onClick={() => setIsExpanded(!isExpanded)}
            className="w-full flex items-center justify-between text-blue-600 hover:text-blue-800 font-medium mb-3"
            >
            <span>Voir la recette</span>
            {isExpanded ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
            </button>

            {isExpanded && (
            <div className="border-t pt-4 space-y-4">
                <div className="space-y-2">
                <h4 className="font-semibold text-gray-700">Ingrédients:</h4>
                {cocktail.Recipe.map((ing, idx) => {
                    const hasIngredient = ing.Type === 'garnish' || barInventory.has(ing.Ingredient);
                    return (
                    <div 
                        key={idx} 
                        className={`flex justify-between text-sm ${
                        !hasIngredient ? 'text-gray-400 line-through' : 'text-gray-700'
                        }`}
                    >
                        <span>{ing.Ingredient}</span>
                        <span className="text-gray-500">
                        {ing.Oz && `${ing.Oz} oz`}
                        {ing.Ml && ` (${ing.Ml} ml)`}
                        </span>
                    </div>
                    );
                })}
                </div>

                {appMode === 'drinker' && currentProfile && available && (
                <button
                    onClick={() => onOrder(cocktail)}
                    className="w-full py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 font-medium"
                >
                    Commander ce cocktail
                </button>
                )}

                {currentProfile && appMode === 'drinker' && (
                <div className="space-y-2">
                    <h4 className="font-semibold text-gray-700">Notes personnelles:</h4>
                    <textarea
                    value={note}
                    onChange={(e) => onSaveNote(cocktail.id, e.target.value)}
                    placeholder="Ajoute tes notes, modifications, commentaires..."
                    className="w-full p-2 border rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    rows={3}
                    />
                </div>
                )}
            </div>
            )}
        </div>
        </div>
    );
};
